package com.ken207.mygit1

const val DIGIT = "."
const val EQUALS = "="
const val PLUS = "+"
const val MINUS = "-"
const val MULTIPLY = "*"
const val DIVIDE = "/"
const val PERCENT = "+"
const val L_BRACKET = "("
const val R_BRACKET = ")"
const val POWER = "power"
const val ROOT = "root"
const val DECIMAL = "decimal"
const val CLEAR = "clear"
const val RESET = "reset"
const val FACTORIAL = "factorial"
